FROM debian
MAINTAINER Felix Fleckenstein
RUN apt-get update && apt-get install -y curl git-core python3 python3-pip libmariadb-dev && curl -sSL https://get.docker.com/ | sh
RUN curl -sL https://deb.nodesource.com/setup_16.x | bash
RUN apt-get install -y build-essential nodejs

RUN git clone https://github.com/FelixFleckenstein/csgo-server-manager.git /opt/
RUN python3 -m pip install -r /opt/api/server_status/requirements.txt
RUN python3 -m pip install -r /opt/api/user_management/requirements.txt
RUN python3 -m pip install python-dotenv
RUN cd /opt/ && npm install && npm install -S react-router-dom && npm install --global yarn

ADD run.sh /opt/run.sh
RUN chmod a+x /opt/run.sh

EXPOSE 3000
CMD /opt/run.sh